name: Auto Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Gets all history instead of just the latest
      
      - name: Run Python
        run: |
          echo "Running latest code:"
          python hello.py
          echo "Build completed successfully!"
